### ISSUE TITLE
Clear selection when user clicks outside of controls

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/build#120]
When I click on the background or outside of any control, I expect that to clear my current control selection.

**Comment by clint-tseng** [comment]
This isn't actually terribly hard to do (3 lines I think), but my question is whether it's really even a good idea. The property sidebar pane is clearly outside the bounds of the control, but clicking anywhere in it really shouldn't deselect the control (imagine misclicking just outside a property textbox and having it deselect the control. Frustrating).

So that leaves the background of just the grey workspace itself. Most of the time, the only grey space available is all the way at the very bottom of the form, or the sliver of grey between controls. If you work with a lot of groups, as it looks like most of our Build users do, even that doesn't count because the sliver between controls is actually part of the group, so the group gets selected.

And Build isn't modal enough (yet?) that deselecting controls has any real utility other than assuaging OCD (which admittedly I too have, so I understand)—pressing arrow keys when selecting a box in Powerpoint moves the box around and when selecting nothing scrolls the slide, for instance, but there is no such behavioural divide in Build.

So between the really scant hit area for the behaviour (which in my estimation actually would make it _more_ confusing when accidentally triggered) and the lack of functional purpose I'm not sure this is actually something we want to do.

**Comment by clint-tseng** [comment]
@lognaturel thoughts here? I would like to close this ticket if you agree.

**Comment by lognaturel** [comment]
Sure, let's close for now.
