### ISSUE TITLE
Update explanation of InvalidText

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/build#123]
Invalid text help says "Message to display if the value fails the length check." That's not accurate. 

The invalid text message is displayed if the answer fails the length check (if you have it) ANDed with the constraint check (if you have it).

**Comment by clint-tseng** [comment]
Does the invalid text message field allow logic? If so we can add a second message field for the constraint and make the feature work more as one would expect rather than patch the help text with a somewhat confusing set of conditions. This, especially in light of #122 which would be another step in this direction.

**Comment by yanokwa** [comment]
Both jr:constraintMsg and jr:requiredMsg are just strings. They do not allow logic.

**Comment by clint-tseng** [comment]
That's too bad. I'll try to think up a different user-friendlier way to remediate.
