### ISSUE TITLE
Can't recall the dataname variable in the hint

### ISSUE THREAD

**Issue by chanchoth** [opendatakit/build#30]
Hi there,

I use the variable in the dataname as province and I would like to call it in the hint by putting ${province} or $province but does not work. How could I do this? Thanks.

**Comment by clint-tseng** [comment]
So, @chanchoth has probably long since forgotten about this ticket :) but `${…}` does in fact work! But you need to use a full XPath expression (eg `${/data/province}`) to make it actually go. The next release of Build will include an inline description of this procedure in the application itself to hopefully expose the feature more and get more folks using it.

I'll close this ticket when that release is out in a few days.

**Comment by clint-tseng** [comment]
Resolved with today's release.
